// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmIY1mamo_CUvbX1lOltouNEMpOfa0WG4',
    appId: '1:1037300845259:web:0e4e01d394f61af6fd294e',
    messagingSenderId: '1037300845259',
    projectId: 'location-tracking-e506e',
    authDomain: 'location-tracking-e506e.firebaseapp.com',
    databaseURL: 'https://location-tracking-e506e-default-rtdb.firebaseio.com',
    storageBucket: 'location-tracking-e506e.appspot.com',
    measurementId: 'G-47X58SMXTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuyCmIO5-89JedApeGY7kNvUSwWuWpGpw',
    appId: '1:317060008870:android:a1e1ab219e8fd98cdf1d67',
    messagingSenderId: '317060008870',
    projectId: 'cartracking-c9d59',
    databaseURL: 'https://cartracking-c9d59-default-rtdb.firebaseio.com/',
    storageBucket: 'cartracking-c9d59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVGGRxmXNg1R6_LlJcbis6pAShpDIa2xY',
    appId: '1:1037300845259:ios:bc6080eaf78e6d4bfd294e',
    messagingSenderId: '1037300845259',
    projectId: 'location-tracking-e506e',
    databaseURL: 'https://location-tracking-e506e-default-rtdb.firebaseio.com',
    storageBucket: 'location-tracking-e506e.appspot.com',
    iosClientId: '1037300845259-eoe5v0pu4shf7t5e1vdrigmh420n9tem.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoMobileTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVGGRxmXNg1R6_LlJcbis6pAShpDIa2xY',
    appId: '1:1037300845259:ios:bc6080eaf78e6d4bfd294e',
    messagingSenderId: '1037300845259',
    projectId: 'location-tracking-e506e',
    databaseURL: 'https://location-tracking-e506e-default-rtdb.firebaseio.com',
    storageBucket: 'location-tracking-e506e.appspot.com',
    iosClientId: '1037300845259-eoe5v0pu4shf7t5e1vdrigmh420n9tem.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoMobileTracker',
  );
}
